spring:
  jpa:
    show-sql: true #쿼리 나오게 설정
    properties:
      hibernate:
        format_sql: true # 쿼리 이쁘게 나오게 설정
  datasource:
    url: jdbc:mysql://localhost:3306/springjpa
    username: root
    password: 1234
    initialization-mode: always
server:
  port: 8090
