spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/springbasic
    username: root
    password: 1234
    initialization-mode: always
server:
  port: 8070
