create or replace FUNCTION       "FC_CHG_FORMAT" (P_STRING IN VARCHAR2, P_TYPE IN VARCHAR2) 
RETURN VARCHAR2 AS
  OUT_STRING VARCHAR2(30);
BEGIN
  BEGIN
    SELECT 
        CASE -- 1: DATE, 11: DATETIME, 2: CO_NO, 3:CARD_NO, 4:FARE
            WHEN P_TYPE = '1' OR P_TYPE='DATE' THEN TO_CHAR(TO_DATE(P_STRING,'YYYYMMDD'),'YYYY-MM-DD')
            WHEN P_TYPE = '11' OR P_TYPE='DATETIME' THEN TO_CHAR(TO_DATE(P_STRING, 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS')
            WHEN P_TYPE = '12' OR P_TYPE='HH24MI' THEN SUBSTR(P_STRING, 0, 2)||':'||SUBSTR(P_STRING, 3, 4)
            WHEN P_TYPE = '13' OR P_TYPE='DATETIME12' THEN TO_CHAR(TO_DATE(P_STRING, 'YYYYMMDDHH24MI'), 'YYYY-MM-DD HH24:MI')
            WHEN P_TYPE = '2' THEN REGEXP_REPLACE(P_STRING, '(\d{3})(\d{2})(\d{5,})', '\1-\2-\3')      
            WHEN P_TYPE = '3' THEN REGEXP_REPLACE(P_STRING, '(\d{4})', '-\1', 5)
            WHEN P_TYPE = '4' THEN (SELECT TO_CHAR(P_STRING, 'FM999,999,999,999') FROM DUAL)
        END
    INTO OUT_STRING
    FROM DUAL;
  RETURN OUT_STRING;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('포맷 변환 중에 오류가 발생했습니다. 변환대상값: ' || P_STRING);
      DBMS_OUTPUT.PUT_LINE('SQL ERROR CODE: ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('SQL ERROR MESSAGE: ' || SQLERRM);
      DBMS_OUTPUT.PUT_LINE(SYS.dbms_utility.format_error_backtrace);
      RETURN '형식오류('||SQLERRM||')';
  END;
END;