spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: jpa-performance-lab

  datasource:
    url: "jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=jpa_study"
    username: "postgres.kxndgixgrlitlnzzcuxd"
    password: "vhxmWkd13!@"
    hikari:
      pool-name: JpaPerformancePool
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        default_schema: jpa_study
        format_sql: true

    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug